import { KeyRound } from 'lucide-react'
import { FormEvent, useState } from 'react'
import Notify from '../../../components/common/notification/notification'
import { Button, cn, Dialog, inputClass } from '../../../design'
import { CredentialType, IssuedCredential, useIssueCredentialMutation } from '../api'
import { apiError } from '../model'
import { FormField } from '../ui'

/**
 * Issues a machine credential for one installation. API keys are generated by
 * Carbonoz and returned once; Keycloak clients are created in the machines
 * realm first and only registered here by client id.
 */
export function IssueCredentialDialog({
  installation,
  onClose,
  onIssued,
}: {
  installation: { id: string; name: string } | null
  onClose: () => void
  onIssued: (c: IssuedCredential) => void
}) {
  const [type, setType] = useState<CredentialType>('API_KEY')
  const [clientId, setClientId] = useState('')
  const [label, setLabel] = useState('')
  const [issue, { isLoading }] = useIssueCredentialMutation()
  const close = () => {
    setType('API_KEY')
    setClientId('')
    setLabel('')
    onClose()
  }
  const submit = async (e: FormEvent) => {
    e.preventDefault()
    if (!installation) return
    try {
      const res = await issue({
        installationId: installation.id,
        type,
        clientId: type === 'KEYCLOAK_CLIENT' ? clientId.trim() : undefined,
        label: label.trim() || undefined,
      }).unwrap()
      close()
      onIssued(res.data)
    } catch (err) {
      Notify({ type: 'error', message: 'Credential not issued', description: apiError(err) })
    }
  }
  const option = (value: CredentialType, title: string, text: string) => (
    <button
      type='button'
      onClick={() => setType(value)}
      aria-pressed={type === value}
      className={cn(
        'flex-1 rounded-xl border px-3.5 py-3 text-left transition-colors',
        type === value ? 'border-accent bg-accent/5' : 'border-line-strong hover:border-subtle',
      )}
    >
      <span className='block text-[13px] font-semibold text-fg'>{title}</span>
      <span className='mt-0.5 block text-[12px] leading-relaxed text-muted'>{text}</span>
    </button>
  )
  return (
    <Dialog
      open={!!installation}
      onClose={close}
      title='Issue machine credential'
      description={installation ? `The credential can only send data for “${installation.name}”. It never grants access to people's accounts or the admin panel.` : undefined}
      footer={
        <>
          <Button variant='ghost' onClick={close}>
            Cancel
          </Button>
          <Button variant='primary' type='submit' form='issue-credential' loading={isLoading} disabled={type === 'KEYCLOAK_CLIENT' && !clientId.trim()}>
            <KeyRound size={15} /> Issue credential
          </Button>
        </>
      }
    >
      <form id='issue-credential' onSubmit={submit} className='space-y-4'>
        <div className='flex flex-col gap-2 sm:flex-row'>
          {option('API_KEY', 'Carbonoz API key', 'Generated here and shown once. Simplest for a single Raspberry Pi.')}
          {option('KEYCLOAK_CLIENT', 'Keycloak client', 'Client-credentials client in the "machines" realm; the secret stays in Keycloak.')}
        </div>
        {type === 'KEYCLOAK_CLIENT' && (
          <FormField label='Keycloak client ID' hint='Create the client in the machines realm first (audience carbonoz-ingest, role solarbms-ingest).'>
            <input className={inputClass} value={clientId} onChange={(e) => setClientId(e.target.value)} placeholder='solarbms-pi-01' required />
          </FormField>
        )}
        <FormField label='Label (optional)' hint='For example where the device is installed.'>
          <input className={inputClass} value={label} onChange={(e) => setLabel(e.target.value)} maxLength={200} />
        </FormField>
      </form>
    </Dialog>
  )
}
